In [11]:
import pandas as pd
df = pd.read_csv('sales-data-sample.csv') #read csv file
df.head(5)

,OrderDate,Category,City,Country,CustomerName,Discount,OrderID,PostalCode,ProductName,Profit,...,DaystoShipActual,SalesForecast,ShipStatus,DaystoShipScheduled,OrderProfitable,SalesperCustomer,ProfitRatio,SalesaboveTarget,latitude,longitude
0,2011-01-04T00:00:00.000Z,Office Supplies,Houston,United States,Darren Powers,0.2,CA-2011-103800,77095,"Message Book, Wirebound, Four 5 1/2 X 4 Forms/...",6,...,4,22,Shipped Early,6,NaN,16.45,33.8,NaN,29.8941,-95.6481
1,2011-01-05T00:00:00.000Z,Office Supplies,Naperville,United States,Phillina Ober,0.2,CA-2011-112326,60540,Avery 508,4,...,4,15,Shipped Early,6,NaN,11.78,36.3,NaN,41.7662,-88.1410
2,2011-01-05T00:00:00.000Z,Office Supplies,Naperville,United States,Phillina Ober,0.8,CA-2011-112326,60540,GBC Standard Plastic Binding Systems Combs,-5,...,4,5,Shipped Early,6,NaN,3.54,-155.0,NaN,41.7662,-88.1410
3,2011-01-05T00:00:00.000Z,Office Supplies,Naperville,United States,Phillina Ober,0.2,CA-2011-112326,60540,SAFCO Boltless Steel Shelving,-65,...,4,357,Shipped Early,6,NaN,272.74,-23.8,NaN,41.7662,-88.1410
4,2011-01-06T00:00:00.000Z,Office Supplies,Philadelphia,United States,Mick Brown,0.2,CA-2011-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,5,...,7,26,Shipped Late,6,NaN,19.54,25.0,NaN,39.9448,-75.2288

In [12]:
columns = list(df.columns) #put columns into a new dataframe
columns

['OrderDate',
 'Category',
 'City',
 'Country',
 'CustomerName',
 'Discount',
 'OrderID',
 'PostalCode',
 'ProductName',
 'Profit',
 'Quantity',
 'Region',
 'Sales',
 'Segment',
 'ShipDate',
 'ShipMode',
 'State',
 'Sub_Category',
 'DaystoShipActual',
 'SalesForecast',
 'ShipStatus',
 'DaystoShipScheduled',
 'OrderProfitable',
 'SalesperCustomer',
 'ProfitRatio',
 'SalesaboveTarget',
 'latitude',
 'longitude']

In [13]:
df_datetime = pd.to_datetime(df["OrderDate"]) ##Cast to Date time format
df_datetime_o = pd.to_datetime(df["ShipDate"]) ##Case to date time format

In [14]:
df_date = df_datetime.dt.date  ##Removing Time from Datetime dataframe
df_date.head()
df_date_o = df_datetime.dt.date
df_date_o.head()

0    2011-01-04
1    2011-01-05
2    2011-01-05
3    2011-01-05
4    2011-01-06
Name: OrderDate, dtype: object

In [15]:
df['Order Date'] = df_date ##Appending the column to df_new
df['Shipping Date'] = df_date_o

In [16]:
df = df.drop(['OrderDate', 'ShipDate', 'OrderProfitable', 'SalesaboveTarget'],axis="columns") ##Drop Extra Columns

In [17]:
df = df.infer_objects() ##infer objects to specific datatypes
df.head()

,Category,City,Country,CustomerName,Discount,OrderID,PostalCode,ProductName,Profit,Quantity,...,DaystoShipActual,SalesForecast,ShipStatus,DaystoShipScheduled,SalesperCustomer,ProfitRatio,latitude,longitude,Order Date,Shipping Date
0,Office Supplies,Houston,United States,Darren Powers,0.2,CA-2011-103800,77095,"Message Book, Wirebound, Four 5 1/2 X 4 Forms/...",6,2,...,4,22,Shipped Early,6,16.45,33.8,29.8941,-95.6481,2011-01-04,2011-01-04
1,Office Supplies,Naperville,United States,Phillina Ober,0.2,CA-2011-112326,60540,Avery 508,4,3,...,4,15,Shipped Early,6,11.78,36.3,41.7662,-88.1410,2011-01-05,2011-01-05
2,Office Supplies,Naperville,United States,Phillina Ober,0.8,CA-2011-112326,60540,GBC Standard Plastic Binding Systems Combs,-5,2,...,4,5,Shipped Early,6,3.54,-155.0,41.7662,-88.1410,2011-01-05,2011-01-05
3,Office Supplies,Naperville,United States,Phillina Ober,0.2,CA-2011-112326,60540,SAFCO Boltless Steel Shelving,-65,3,...,4,357,Shipped Early,6,272.74,-23.8,41.7662,-88.1410,2011-01-05,2011-01-05
4,Office Supplies,Philadelphia,United States,Mick Brown,0.2,CA-2011-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,5,3,...,7,26,Shipped Late,6,19.54,25.0,39.9448,-75.2288,2011-01-06,2011-01-06

In [18]:
df.info() ##check for the datatypes of dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Category             9994 non-null   object
 1   City                 9994 non-null   object
 2   Country              9994 non-null   object
 3   CustomerName         9994 non-null   object
 4   Discount             9994 non-null   float64
 5   OrderID              9994 non-null   object
 6   PostalCode           9994 non-null   int64
 7   ProductName          9994 non-null   object
 8   Profit               9994 non-null   int64
 9   Quantity             9994 non-null   int64
 10  Region               9994 non-null   object
 11  Sales                9994 non-null   int64
 12  Segment              9994 non-null   object
 13  ShipMode             9994 non-null   object
 14  State                9994 non-null   object
 15  Sub_Category         9994 non-null   object
 16  DaystoShipActual     9994 non-null   int64
 17  SalesForecast        9994 non-null   int64
 18  ShipStatus           9994 non-null   object
 19  DaystoShipScheduled  9994 non-null   int64
 20  SalesperCustomer     9994 non-null   float64
 21  ProfitRatio          9994 non-null   float64
 22  latitude             9994 non-null   float64
 23  longitude            9994 non-null   float64
 24  Order Date           9994 non-null   object
 25  Shipping Date        9994 non-null   object
dtypes: float64(5), int64(7), object(14)
memory usage: 2.0+ MB

In [19]:
df.to_csv('CleanedSalesData.csv',index='false') ##Export the cleaned data to csv